CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS "countries"
(
    id   UUID UNIQUE         NOT NULL DEFAULT uuid_generate_v4() PRIMARY KEY,
    code CHAR(2) UNIQUE      NOT NULL,
    name VARCHAR(255) UNIQUE NOT NULL
);

COMMENT ON COLUMN countries.code is 'Two-letter country code (ISO 3166-1 alpha-2)';
COMMENT ON COLUMN countries.name is 'English country name';

INSERT INTO countries (code, name)
VALUES ('AF', 'Islamic Republic of Afghanistan'),
       ('AX', 'Åland Islands'),
       ('AL', 'Republic of Albania'),
       ('DZ', 'People''s Democratic Republic of Algeria'),
       ('AS', 'American Samoa'),
       ('AD', 'Principality of Andorra'),
       ('AO', 'Republic of Angola'),
       ('AI', 'Anguilla'),
       ('AQ', 'Antarctica (the territory South of 60 deg S)'),
       ('AG', 'Antigua and Barbuda'),
       ('AR', 'Argentine Republic'),
       ('AM', 'Republic of Armenia'),
       ('AW', 'Aruba'),
       ('AU', 'Commonwealth of Australia'),
       ('AT', 'Republic of Austria'),
       ('AZ', 'Republic of Azerbaijan'),
       ('BS', 'Commonwealth of the Bahamas'),
       ('BH', 'Kingdom of Bahrain'),
       ('BD', 'People''s Republic of Bangladesh'),
       ('BB', 'Barbados'),
       ('BY', 'Republic of Belarus'),
       ('BE', 'Kingdom of Belgium'),
       ('BZ', 'Belize'),
       ('BJ', 'Republic of Benin'),
       ('BM', 'Bermuda'),
       ('BT', 'Kingdom of Bhutan'),
       ('BO', 'Plurinational State of Bolivia'),
       ('BQ', 'Bonaire, Sint Eustatius and Saba'),
       ('BA', 'Bosnia and Herzegovina'),
       ('BW', 'Republic of Botswana'),
       ('BV', 'Bouvet Island (Bouvetoya)'),
       ('BR', 'Federative Republic of Brazil'),
       ('IO', 'British Indian Ocean Territory (Chagos Archipelago)'),
       ('VG', 'British Virgin Islands'),
       ('BN', 'Brunei Darussalam'),
       ('BG', 'Republic of Bulgaria'),
       ('BF', 'Burkina Faso'),
       ('BI', 'Republic of Burundi'),
       ('KH', 'Kingdom of Cambodia'),
       ('CM', 'Republic of Cameroon'),
       ('CA', 'Canada'),
       ('CV', 'Republic of Cape Verde'),
       ('KY', 'Cayman Islands'),
       ('CF', 'Central African Republic'),
       ('TD', 'Republic of Chad'),
       ('CL', 'Republic of Chile'),
       ('CN', 'People''s Republic of China'),
       ('CX', 'Christmas Island'),
       ('CC', 'Cocos (Keeling) Islands'),
       ('CO', 'Republic of Colombia'),
       ('KM', 'Union of the Comoros'),
       ('CD', 'Democratic Republic of the Congo'),
       ('CG', 'Republic of the Congo'),
       ('CK', 'Cook Islands'),
       ('CR', 'Republic of Costa Rica'),
       ('CI', 'Republic of Cote d''Ivoire'),
       ('HR', 'Republic of Croatia'),
       ('CU', 'Republic of Cuba'),
       ('CW', 'Curaçao'),
       ('CY', 'Republic of Cyprus'),
       ('CZ', 'Czech Republic'),
       ('DK', 'Kingdom of Denmark'),
       ('DJ', 'Republic of Djibouti'),
       ('DM', 'Commonwealth of Dominica'),
       ('DO', 'Dominican Republic'),
       ('EC', 'Republic of Ecuador'),
       ('EG', 'Arab Republic of Egypt'),
       ('SV', 'Republic of El Salvador'),
       ('GQ', 'Republic of Equatorial Guinea'),
       ('ER', 'State of Eritrea'),
       ('EE', 'Republic of Estonia'),
       ('ET', 'Federal Democratic Republic of Ethiopia'),
       ('FO', 'Faroe Islands'),
       ('FK', 'Falkland Islands (Malvinas)'),
       ('FJ', 'Republic of Fiji'),
       ('FI', 'Republic of Finland'),
       ('FR', 'French Republic'),
       ('GF', 'French Guiana'),
       ('PF', 'French Polynesia'),
       ('TF', 'French Southern Territories'),
       ('GA', 'Gabonese Republic'),
       ('GM', 'Republic of the Gambia'),
       ('GE', 'Georgia'),
       ('DE', 'Federal Republic of Germany'),
       ('GH', 'Republic of Ghana'),
       ('GI', 'Gibraltar'),
       ('GR', 'Hellenic Republic Greece'),
       ('GL', 'Greenland'),
       ('GD', 'Grenada'),
       ('GP', 'Guadeloupe'),
       ('GU', 'Guam'),
       ('GT', 'Republic of Guatemala'),
       ('GG', 'Bailiwick of Guernsey'),
       ('GN', 'Republic of Guinea'),
       ('GW', 'Republic of Guinea-Bissau'),
       ('GY', 'Co-operative Republic of Guyana'),
       ('HT', 'Republic of Haiti'),
       ('HM', 'Heard Island and McDonald Islands'),
       ('VA', 'Holy See (Vatican City State)'),
       ('HN', 'Republic of Honduras'),
       ('HK', 'Hong Kong Special Administrative Region of China'),
       ('HU', 'Hungary'),
       ('IS', 'Republic of Iceland'),
       ('IN', 'Republic of India'),
       ('ID', 'Republic of Indonesia'),
       ('IR', 'Islamic Republic of Iran'),
       ('IQ', 'Republic of Iraq'),
       ('IE', 'Ireland'),
       ('IM', 'Isle of Man'),
       ('IL', 'State of Israel'),
       ('IT', 'Italian Republic'),
       ('JM', 'Jamaica'),
       ('JP', 'Japan'),
       ('JE', 'Bailiwick of Jersey'),
       ('JO', 'Hashemite Kingdom of Jordan'),
       ('KZ', 'Republic of Kazakhstan'),
       ('KE', 'Republic of Kenya'),
       ('KI', 'Republic of Kiribati'),
       ('KP', 'Democratic People''s Republic of Korea'),
       ('KR', 'Republic of Korea'),
       ('KW', 'State of Kuwait'),
       ('KG', 'Kyrgyz Republic'),
       ('LA', 'Lao People''s Democratic Republic'),
       ('LV', 'Republic of Latvia'),
       ('LB', 'Lebanese Republic'),
       ('LS', 'Kingdom of Lesotho'),
       ('LR', 'Republic of Liberia'),
       ('LY', 'Libya'),
       ('LI', 'Principality of Liechtenstein'),
       ('LT', 'Republic of Lithuania'),
       ('LU', 'Grand Duchy of Luxembourg'),
       ('MO', 'Macao Special Administrative Region of China'),
       ('MK', 'Republic of Macedonia'),
       ('MG', 'Republic of Madagascar'),
       ('MW', 'Republic of Malawi'),
       ('MY', 'Malaysia'),
       ('MV', 'Republic of Maldives'),
       ('ML', 'Republic of Mali'),
       ('MT', 'Republic of Malta'),
       ('MH', 'Republic of the Marshall Islands'),
       ('MQ', 'Martinique'),
       ('MR', 'Islamic Republic of Mauritania'),
       ('MU', 'Republic of Mauritius'),
       ('YT', 'Mayotte'),
       ('MX', 'United Mexican States'),
       ('FM', 'Federated States of Micronesia'),
       ('MD', 'Republic of Moldova'),
       ('MC', 'Principality of Monaco'),
       ('MN', 'Mongolia'),
       ('ME', 'Montenegro'),
       ('MS', 'Montserrat'),
       ('MA', 'Kingdom of Morocco'),
       ('MZ', 'Republic of Mozambique'),
       ('MM', 'Republic of the Union of Myanmar'),
       ('NA', 'Republic of Namibia'),
       ('NR', 'Republic of Nauru'),
       ('NP', 'Federal Democratic Republic of Nepal'),
       ('NL', 'Kingdom of the Netherlands'),
       ('NC', 'New Caledonia'),
       ('NZ', 'New Zealand'),
       ('NI', 'Republic of Nicaragua'),
       ('NE', 'Republic of Niger'),
       ('NG', 'Federal Republic of Nigeria'),
       ('NU', 'Niue'),
       ('NF', 'Norfolk Island'),
       ('MP', 'Commonwealth of the Northern Mariana Islands'),
       ('NO', 'Kingdom of Norway'),
       ('OM', 'Sultanate of Oman'),
       ('PK', 'Islamic Republic of Pakistan'),
       ('PW', 'Republic of Palau'),
       ('PS', 'State of Palestine'),
       ('PA', 'Republic of Panama'),
       ('PG', 'Independent State of Papua New Guinea'),
       ('PY', 'Republic of Paraguay'),
       ('PE', 'Republic of Peru'),
       ('PH', 'Republic of the Philippines'),
       ('PN', 'Pitcairn Islands'),
       ('PL', 'Republic of Poland'),
       ('PT', 'Portuguese Republic'),
       ('PR', 'Commonwealth of Puerto Rico'),
       ('QA', 'State of Qatar'),
       ('RE', 'Réunion'),
       ('RO', 'Romania'),
       ('RU', 'Russian Federation'),
       ('RW', 'Republic of Rwanda'),
       ('BL', 'Saint Barthélemy'),
       ('SH', 'Saint Helena, Ascension and Tristan da Cunha'),
       ('KN', 'Federation of Saint Kitts and Nevis'),
       ('LC', 'Saint Lucia'),
       ('MF', 'Saint Martin (French part)'),
       ('PM', 'Saint Pierre and Miquelon'),
       ('VC', 'Saint Vincent and the Grenadines'),
       ('WS', 'Independent State of Samoa'),
       ('SM', 'Republic of San Marino'),
       ('ST', 'Democratic Republic of Sao Tome and Principe'),
       ('SA', 'Kingdom of Saudi Arabia'),
       ('SN', 'Republic of Senegal'),
       ('RS', 'Republic of Serbia'),
       ('SC', 'Republic of Seychelles'),
       ('SL', 'Republic of Sierra Leone'),
       ('SG', 'Republic of Singapore'),
       ('SX', 'Sint Maarten (Dutch part)'),
       ('SK', 'Slovakia (Slovak Republic)'),
       ('SI', 'Republic of Slovenia'),
       ('SB', 'Solomon Islands'),
       ('SO', 'Federal Republic of Somalia'),
       ('ZA', 'Republic of South Africa'),
       ('GS', 'South Georgia and the South Sandwich Islands'),
       ('SS', 'Republic of South Sudan'),
       ('ES', 'Kingdom of Spain'),
       ('LK', 'Democratic Socialist Republic of Sri Lanka'),
       ('SD', 'Republic of Sudan'),
       ('SR', 'Republic of Suriname'),
       ('SJ', 'Svalbard & Jan Mayen Islands'),
       ('SZ', 'Kingdom of Swaziland'),
       ('SE', 'Kingdom of Sweden'),
       ('CH', 'Swiss Confederation'),
       ('SY', 'Syrian Arab Republic'),
       ('TW', 'Taiwan, Province of China'),
       ('TJ', 'Republic of Tajikistan'),
       ('TZ', 'United Republic of Tanzania'),
       ('TH', 'Kingdom of Thailand'),
       ('TL', 'Democratic Republic of Timor-Leste'),
       ('TG', 'Togolese Republic'),
       ('TK', 'Tokelau'),
       ('TO', 'Kingdom of Tonga'),
       ('TT', 'Republic of Trinidad and Tobago'),
       ('TN', 'Tunisian Republic'),
       ('TR', 'Republic of Turkey'),
       ('TM', 'Turkmenistan'),
       ('TC', 'Turks and Caicos Islands'),
       ('TV', 'Tuvalu'),
       ('UG', 'Republic of Uganda'),
       ('UA', 'Ukraine'),
       ('AE', 'United Arab Emirates'),
       ('GB', 'United Kingdom of Great Britain & Northern Ireland'),
       ('US', 'United States of America'),
       ('UM', 'United States Minor Outlying Islands'),
       ('VI', 'United States Virgin Islands'),
       ('UY', 'Eastern Republic of Uruguay'),
       ('UZ', 'Republic of Uzbekistan'),
       ('VU', 'Republic of Vanuatu'),
       ('VE', 'Bolivarian Republic of Venezuela'),
       ('VN', 'Socialist Republic of Vietnam'),
       ('WF', 'Wallis and Futuna'),
       ('EH', 'Western Sahara'),
       ('YE', 'Yemen'),
       ('ZM', 'Republic of Zambia'),
       ('ZW', 'Republic of Zimbabwe');
